In [1]:
# read data
from sklearn import datasets
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()
X = iris.data
Y = iris.target

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [2]:
# 获得先验概率prior和条件概率condition
import numpy as np
import scipy.stats as st
# prior=p(Y=ck)
class_num = np.unique(Y_train)
sample_num = len(Y_train)
y_count = np.array([np.sum(Y_train==k) for k in class_num])
prior = y_count / sample_num
print('prior:', prior)
# 首先求各个类中每个特征的均值和方差
mean=np.array([np.mean(X_train[np.where(Y_train==k)], axis=0) for k in class_num])
print('mean:', mean)
std=np.array([np.std(X_train[np.where(Y_train==k)], axis=0) for k in class_num])
print('std:', std)
feature_num = X_train.shape[1]
# condition=p(x=xj|y=ck)
# 后验概率post=P(y=ck)*condition的连乘
post_p = np.zeros([X_test.shape[0], len(class_num)])
i=0
for sample in X_test:
    for k in range(len(class_num)):
        prod = 1
        for j in range(feature_num):
            prod *= st.norm.pdf(sample[j], mean[k][j], std[k][j])
        post_p[i][k]=prod*prior[k]
    i+=1
y = np.argmax(post_p, axis=1)
accuracy = np.sum(Y_test==y)/len(X_test)
print()
print('accuracy:', accuracy)
print('error sample index:', np.where(Y_test!=y))

prior: [0.31 0.35 0.34]
mean: [[4.96451613 3.37741935 1.46451613 0.2483871 ]
 [5.85142857 2.72571429 4.22       1.30857143]
 [6.55294118 2.97058824 5.54411765 2.01176471]]
std: [[0.33461426 0.36957663 0.18236508 0.10737624]
 [0.52119173 0.29504756 0.49442607 0.20194968]
 [0.66696648 0.30344048 0.54675039 0.27840375]]

accuracy: 0.96
error sample index: (array([15, 46], dtype=int64),)
