In [26]:
# read data
import pandas as pd
from sklearn.feature_extraction import DictVectorizer

data = pd.read_csv("PlayTennis.csv")
# 通过DictVectorizer，我们就能够把字符型的数据，转化成0 1的矩阵，方便后面进行运算。
vec = DictVectorizer(sparse=False)
feature = data[['outlook', 'temp', 'humidity', 'windy']]
x_train = vec.fit_transform(feature.to_dict(orient='record'))
y_train = data['play'].to_numpy()
print(feature)
print(x_train)
print(y_train)

     outlook  temp humidity  windy
0      sunny   hot     high  False
1      sunny   hot     high   True
2   overcast   hot     high  False
3      rainy  mild     high  False
4      rainy  cool   normal  False
5      rainy  cool   normal   True
6   overcast  cool   normal   True
7      sunny  mild     high  False
8      sunny  cool   normal  False
9      rainy  mild   normal  False
10     sunny  mild   normal   True
11  overcast  mild     high   True
12  overcast   hot   normal  False
13     rainy  mild     high   True
[[1. 0. 0. 0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 1.]
 [1. 0. 1. 0. 0. 0. 0. 1. 1.]
 [0. 1. 1. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 1.]]
['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'ye

In [27]:
from sklearn.model_selection import train_test_split
from sklearn import tree
# decision tree

# 划分数据集
# x_trian, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
clf = tree.DecisionTreeClassifier(criterion='gini')
clf.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [28]:
# 可视化
with open("out.dot", "w") as f:
    f = tree.export_graphviz(clf, out_file = f, feature_names=vec.get_feature_names())
# 需要安装Graphviz，到官网下载即可
# 安装完成后，去Graphviz的下载目录，去bin文件夹
# 执行dot out.dot -T pdf -o out.pdf 得到输出pdf文件

# 结果
![decision tree](out.jpg)